language: scala
scala:
  - "2.10.6"
  - "2.11.8"
jdk:
  - oraclejdk8
script:
  - sbt -Dkontextfrei.spark.version=1.4.1 clean test
  - sbt -Dkontextfrei.spark.version=2.0.0 clean test
  - sbt -Dkontextfrei.spark.version=2.1.0
  - sbt -Dkontextfrei.spark.version=2.2.0 clean coverage test coverageReport && sbt coverageAggregate
after_success:
  - bash <(curl -s https://codecov.io/bash)
